const state={joined:false,adult:false,room:'1',stream:null,raffle:3,saved:false,mic:true,ai:true};
const screen=document.getElementById('screen'),broadcastMenu=document.getElementById('broadcastMenu'),creator=document.getElementById('creator'),camera=document.getElementById('camera'),sheet=document.getElementById('sheet'),sheetTitle=document.getElementById('sheetTitle'),sheetBody=document.getElementById('sheetBody');
function activate(name){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name))}
document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t){activate(t.dataset.tab);render(t.dataset.tab);return}const b=e.target.closest('[data-bottom]');if(b){const k=b.dataset.bottom;if(k==='home'){activate('home');home()}if(k==='friends')friends();if(k==='plus')openBroadcastMenu();if(k==='help')openMenu();if(k==='profile')openProfile();return}const p=e.target.closest('[data-roompick]');if(p){state.room=p.dataset.roompick;document.querySelectorAll('[data-roompick]').forEach(x=>x.classList.toggle('on',x===p))}})
function render(name){if(name==='home')home();if(name==='rooms')rooms();if(name==='shorts'||name==='video')media(name);if(name==='profile')openProfile()}
function home(){screen.innerHTML='<section class="live-view"><div class="live-top"><i class="backdot"></i><b>지금 방송 중 · 1인 방송</b><span>LIVE</span></div><div class="room-led">♛ K-Talk · 신곡 광고 신청하세요! 🎵 🎤</div><div class="live-stage"><div class="host-visual">🎤</div><button class="join-chip" onclick="needJoin(\'방송을 보면서 가입하면 댓글·쪽지·선물을 이용할 수 있습니다.\')">방송 보다가 가입하기</button><div class="host-meta"><b>♛ 태권</b><span>현재 방송 중</span></div><div class="chat-bubbles"><span>하늘별 · 안녕하세요 💕</span><span>미소 · 오늘 방송 좋아요!</span></div><div class="right-actions"><button onclick="needJoin(\'좋아요를 누르려면 가입해 주세요.\')">♡<small>좋아요</small></button><button onclick="openComments()">💬<small>댓글</small></button><button onclick="toggleSave(this)">☆<small>저장</small></button><button onclick="shareApp()">↗<small>공유</small></button></div><div class="quick-gifts"><button onclick="openGifts()"><strong>🌹</strong>장미</button><button onclick="openGifts()"><strong>💐</strong>꽃다발</button><button onclick="openTreasure()"><strong>🎁</strong>보물상자</button><button onclick="openGifts()"><strong>👑</strong>큰 선물</button></div></div></section>'}
function friends(){
 const data=[
  {name:'하늘별',on:true,room:'1인 방송'},
  {name:'미소',on:true,room:'13명 방송'},
  {name:'행복이',on:true,room:'구독자방'},
  {name:'달빛',on:false,room:'대기'},
  {name:'바다',on:false,room:'대기'},
  {name:'좋은날',on:false,room:'대기'}
 ];
 const top=data.map(x=>'<button class="friend-story '+(x.on?'on':'off')+'" onclick="'+(x.on?'home()':'void(0)')+'"><span>'+x.name[0]+'</span><small>'+x.name+'</small></button>').join('');
 const rows=data.map(x=>'<div class="friend-row"><div class="friend-avatar '+(x.on?'on':'off')+'">'+x.name[0]+'</div><div class="friend-info"><b>'+x.name+'</b><span>'+(x.on?'🔴 방송 중 · '+x.room:'🔵 방송 안 함')+'</span></div><button onclick="'+(x.on?'home()':'openMessages()')+'">'+(x.on?'방송 보기':'쪽지')+'</button></div>').join('');
 screen.innerHTML='<section class="friends-page"><div class="friends-head"><b>친구</b><button>⌕</button></div><div class="friends-stories">'+top+'</div><div class="friends-label"><b>팔로우한 사람</b><span>방송 중은 빨강 · 방송 안 함은 파랑</span></div><div class="friends-list">'+rows+'</div></section>';
}
function rooms(){screen.innerHTML='<section class="room-menu">'+roomCard('1','1인 방송',1,'one','')+roomCard('2','13명 방송',13,'t13','g12')+roomCard('3','구독자방',9,'t9','g8')+roomCard('4','비밀방',6,'t6','g5')+'</section>'}
function roomCard(id,name,total,cls,gcls){let guests='';for(let i=1;i<total;i++)guests+='<i></i>';return '<button class="room-card" onclick="enterRoom(\''+id+'\')"><b>'+id+'번 · '+name+'</b><small>총 '+total+'명 · 호스트 포함</small><span class="mini-layout '+cls+'"><span class="mini-host">♛</span>'+(total>1?'<span class="mini-guests '+gcls+'">'+guests+'</span>':'')+'</span></button>'}
function enterRoom(id){if((id==='3'||id==='4')&&!state.joined){needJoin('이 방은 가입 후 이용할 수 있습니다.');return}const c=id==='1'?['1인 방송',1,'solo',0,'']:id==='2'?['13명 방송',13,'r13',12,'g12']:id==='3'?['구독자방',9,'r9',8,'g8']:['비밀방',6,'r6',5,'g5'];let guests='';for(let i=1;i<=c[3];i++)guests+='<div class="guest">참여자 '+i+'</div>';const gate=id==='4'?'<div class="secret-gate"><input placeholder="비밀번호 입력"><button>비밀방 입장</button></div>':'';screen.innerHTML='<section class="room-view"><div class="room-head"><button onclick="rooms()">←</button><div><b>'+c[0]+'</b><small>총 '+c[1]+'명 · 호스트 포함</small></div><button onclick="openMessages()">✉</button></div><div class="room-led">♛ K-Talk · 신곡 광고 신청하세요! 🎵 🎤</div><div class="room-body '+c[2]+'"><div class="host-box"><span class="onair">ON AIR</span><em>🎤</em><span class="hn">♛ 태권 · HOST</span></div>'+(c[3]?'<div class="guest-grid '+c[4]+'">'+guests+'</div>':'')+'<div class="room-chat"><span>하늘별 · 안녕하세요 💕</span><span>미소 · 오늘 방송 좋아요!</span><span>행복이 · 응원합니다 👍</span></div><div class="room-side"><button onclick="needJoin(\'좋아요를 누르려면 가입해 주세요.\')">♡</button><button onclick="openComments()">💬</button><button onclick="report()">⚑</button></div>'+gate+'</div><div class="room-tools"><button onclick="openCreator()">📷 카메라</button><button onclick="openAI()">🔊 AI 읽기</button><button onclick="openSong()">🎵 노래</button><button onclick="toggleMic(this)">🎤 마이크</button></div><div class="gift-dock"><button onclick="openGifts()"><strong>🌹</strong>장미</button><button onclick="openGifts()"><strong>💐</strong>꽃다발</button><button onclick="openTreasure()"><strong>🎁</strong>보물상자</button><button onclick="openGifts()"><strong>💖</strong>하트</button><button onclick="openGifts()"><strong>👑</strong>왕관</button><button onclick="openGifts()"><strong>🚗</strong>자동차</button><button onclick="openGifts()"><strong>✨</strong>큰 선물</button></div></section>'}
function media(type){const label=type==='shorts'?'쇼츠':'동영상';screen.innerHTML='<section class="media"><div class="play">▶</div><div class="host-meta"><b>♛ 태권</b><span>'+label+'을 올리면 이곳에 표시됩니다.</span></div><div class="right-actions"><button onclick="needJoin(\'좋아요를 누르려면 가입해 주세요.\')">♡<small>좋아요</small></button><button onclick="openComments()">💬<small>댓글</small></button><button onclick="toggleSave(this)">☆<small>저장</small></button><button onclick="shareApp()">↗<small>공유</small></button></div></section>'}
function openBroadcastMenu(){broadcastMenu.classList.add('show')}
function closeBroadcastMenu(){broadcastMenu.classList.remove('show')}
function selectRoomAndCamera(id){state.room=id;closeBroadcastMenu();openCreator()}
function openMediaFromBroadcast(type){closeBroadcastMenu();activate(type);media(type)}
async function openCreator(){creator.classList.add('show');try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});camera.srcObject=state.stream}catch(e){}}
function closeCreator(){creator.classList.remove('show');if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null;camera.srcObject=null}}
function startBroadcast(){if(!state.joined){closeCreator();needJoin('방송을 시작하려면 먼저 가입과 성인 인증이 필요합니다.');return}closeCreator();activate('rooms');enterRoom(state.room)}
function showSheet(title,html){sheetTitle.innerHTML=title;sheetBody.innerHTML=html;sheet.classList.add('show')}function closeSheet(){sheet.classList.remove('show')}
function needJoin(msg){showSheet('가입하기','<div class="note">'+msg+'</div><button class="act social naver" onclick="join(\'네이버\')">네이버로 계속하기</button><button class="act social kakao" onclick="join(\'카카오\')">카카오로 계속하기</button><button class="act social google" onclick="join(\'Google\')">Google로 계속하기</button><div class="note">실제 서비스에서는 소셜 로그인과 휴대폰 성인 인증 연결 후 완료됩니다.</div>')}
function join(p){state.joined=true;showSheet('성인 인증','<div class="rowbox"><b>'+p+' 로그인 연결</b><div class="note">로그인 완료 후 휴대폰 본인인증을 진행합니다.</div></div><button class="act" onclick="finishJoin()">휴대폰 본인인증 완료</button>')}
function finishJoin(){state.adult=true;closeSheet()}
function openMenu(){showSheet('K-Talk 사용방법·혜택','<div class="aux-grid"><button class="aux-card" onclick="openGifts()"><b>🎁 선물·보물상자</b><small>장미부터 큰 선물</small></button><button class="aux-card" onclick="openCharge()"><b>🌹 장미 충전</b><small>충전 수량·구독 할인</small></button><button class="aux-card" onclick="openSubs()"><b>👑 구독·VIP</b><small>구독 등급과 혜택</small></button><button class="aux-card" onclick="openRaffle()"><b>🎯 제비뽑기</b><small>하루 3회</small></button><button class="aux-card" onclick="openMessages()"><b>✉ 쪽지</b><small>받고 보내기</small></button><button class="aux-card" onclick="openProfile()"><b>♛ 프로필</b><small>팔로우·링크·콘텐츠</small></button><button class="aux-card" onclick="openAI()"><b>🔊 AI 읽기</b><small>닉네임·채팅 읽기</small></button><button class="aux-card" onclick="openSong()"><b>🎵 노래·배경</b><small>무대·산·바다</small></button><button class="aux-card" onclick="report()"><b>🚩 신고 게시판</b><small>회사 관리자 처리</small></button><button class="aux-card" onclick="openAd()"><b>📣 광고·판매자</b><small>광고/사업자 등록</small></button></div>')}
function openGifts(){showSheet('🎁 K-Talk 선물','<div class="gift-grid"><button class="gift-big"><span>🌹</span><b>장미 1</b></button><button class="gift-big"><span>💐</span><b>장미 5</b></button><button class="gift-big"><span>🎁</span><b>장미 10</b></button><button class="gift-big"><span>🌼</span><b>황금 꽃다발</b></button><button class="gift-big"><span>💖</span><b>로열 하트</b></button><button class="gift-big"><span>👑</span><b>왕관</b></button></div><div class="premium-grid"><button class="premium"><span>💎👑</span><b>다이아 왕관</b></button><button class="premium"><span>🏎️</span><b>럭셔리 자동차</b></button><button class="premium"><span>🛥️</span><b>로열 요트</b></button><button class="premium"><span>🏰</span><b>골든 캐슬</b></button><button class="premium"><span>🌌</span><b>갤럭시 무대</b></button><button class="premium" onclick="openTreasure()"><span>🎁</span><b>보물상자</b></button></div>')}
function openTreasure(){showSheet('🎁 보물상자','<div class="premium-grid"><button class="premium"><span>🎁</span><b>보물상자 50</b></button><button class="premium"><span>🎁</span><b>보물상자 100</b></button><button class="premium"><span>🎁</span><b>보물상자 150</b></button><button class="premium"><span>💖</span><b>하트 100</b></button><button class="premium"><span>💞</span><b>하트 500</b></button><button class="premium"><span>💗</span><b>하트 1000</b></button></div><div class="note">방송 시작 전에 하트 배경 효과를 선택하면 방송 뒤에 자동으로 표시되게 연결하는 자리입니다.</div>')}
function openCharge(){showSheet('🌹 장미 충전','<div class="rowbox"><b>장미 1개 = 30원 기준</b></div>'+[[100,110],[200,210],[300,310],[500,510],[1000,1010],[2000,2010]].map(x=>'<div class="rowbox"><b>'+x[0]+'개</b> · 서비스 포함 '+x[1]+'개</div>').join('')+'<div class="rowbox"><b>10만원 · 4,000개</b></div><div class="note">구독자는 500개 이상 충전 시 15% 할인 기준.</div>')}
function openSubs(){showSheet('👑 구독·회원 혜택','<div class="rowbox"><b>일반 구독자</b><br>월 5,000원</div><div class="rowbox"><b>중회원</b><br>월 14,900원</div><div class="rowbox"><b>VIP</b><br>월 19,900원</div><div class="note">구독자는 비밀방·구독자방 이용 허용, 500개 이상 충전 시 15% 할인 기준.</div>')}
function openRaffle(){showSheet('🎯 제비뽑기','<div class="raffle">꽝 · 1 · 2 · 3 · 4 · 5</div><button class="act" onclick="raffle()">제비뽑기</button><div class="note">아침·점심·저녁 하루 3회. 꽝 2칸, 장미 1~5개.</div>')}
function raffle(){if(state.raffle<=0)return alert('오늘 참여 횟수를 모두 사용했습니다.');state.raffle--;const p=[0,0,1,2,3,4,5],x=p[Math.floor(Math.random()*p.length)];alert(x?'장미 '+x+'개 당첨!':'꽝입니다.')}
function openMessages(){if(!state.joined){needJoin('쪽지를 확인하고 보내려면 가입해 주세요.');return}showSheet('✉ 쪽지','<div class="rowbox"><b>하늘별</b><br>방송 잘 보고 있어요.</div><div class="rowbox"><b>미소</b><br>오늘 방송하시나요?</div><input class="form" placeholder="쪽지 내용을 입력하세요"><button class="act">쪽지 보내기</button>')}
function openComments(){if(!state.joined){needJoin('댓글을 쓰려면 가입해 주세요.');return}showSheet('💬 댓글','<div class="rowbox"><b>하늘별</b> 안녕하세요 💕</div><div class="rowbox"><b>미소</b> 오늘 방송 좋아요!</div><input class="form" placeholder="댓글 입력"><button class="act">댓글 보내기</button>')}
function openProfile(){showSheet('♛ 태권 프로필','<div class="profile-pic">태</div><div style="text-align:center"><h3 style="margin:8px 0 2px;color:#ffe07a">♛ 태권</h3><div class="note">K-Talk LIVE</div></div><div class="stats"><div><b>0</b><span>팔로워</span></div><div><b>30</b><span>팔로잉</span></div><div><b>Lv.1</b><span>레벨</span></div></div><input class="form" placeholder="홈페이지·블로그·SNS 링크"><button class="act">프로필 링크 저장</button><div class="aux-grid"><button class="aux-card" onclick="activate(\'video\');closeSheet();media(\'video\')"><b>동영상</b><small>내 동영상</small></button><button class="aux-card" onclick="activate(\'shorts\');closeSheet();media(\'shorts\')"><b>쇼츠</b><small>내 쇼츠</small></button></div>')}
function openAI(){showSheet('🔊 AI 읽기','<div class="rowbox"><b>AI 읽기 보조</b><div class="note">닉네임 → 채팅 내용 → 선물 알림 순서로 자연스럽게 읽습니다. 오타·띄어쓰기는 문맥으로 보정하고, 불확실하면 임의로 추측하지 않습니다.</div></div><button class="act" onclick="state.ai=!state.ai;this.textContent=state.ai?\'AI 읽기 켜짐\':\'AI 읽기 꺼짐\'">AI 읽기 켜짐</button>')}
function openSong(){showSheet('🎵 노래·배경','<div class="rowbox"><b>노래 모드</b><div class="note">노래 시작 시 일반 참여자 마이크 자동 잠금, 노래 종료 후 자동 해제. 호스트·운영진은 직접 관리.</div></div><div class="aux-grid"><button class="aux-card"><b>🎤 무대</b><small>콘서트 무대</small></button><button class="aux-card"><b>🏔️ 산</b><small>자연 배경</small></button><button class="aux-card"><b>🌊 바다</b><small>바다 배경</small></button><button class="aux-card"><b>🌃 야경</b><small>도시 야경</small></button><button class="aux-card"><b>🌸 꽃밭</b><small>꽃 배경</small></button><button class="aux-card"><b>🌌 우주</b><small>별빛 무대</small></button></div>')}
function report(){showSheet('🚩 회사 관리 신고 게시판','<input class="form" placeholder="신고 대상 닉네임"><select class="form"><option>위험한 행동</option><option>욕설·괴롭힘</option><option>사칭</option><option>불법 판매</option><option>기타</option></select><input class="form" placeholder="신고 내용"><button class="act">신고 접수</button><div class="note">접수 → 확인 중 → 경고/이용정지 → 처리 완료</div>')}
function openAd(){showSheet('📣 광고·판매자 등록','<div class="rowbox"><b>광고</b><br>한 달 300,000원</div><div class="rowbox"><b>물건 판매자</b><br>사업자등록증 확인 · 매월 1일~말일 300,000원</div><div class="note">결제·환불 정책은 실제 서비스 약관과 관련 법규에 맞춰 별도 고지하도록 연결합니다.</div><button class="act">광고 문의</button>')}
function toggleSave(btn){state.saved=!state.saved;btn.style.color=state.saved?'#ffe07a':'#fff'}function toggleMic(btn){state.mic=!state.mic;btn.textContent=state.mic?'🎤 마이크':'🔇 마이크'}function shareApp(){if(navigator.share)navigator.share({title:'K-Talk LIVE',text:'K-Talk LIVE 방송을 확인해 보세요'}).catch(()=>{});else alert('공유 메뉴를 열었습니다.')}
home();